version: '3'
networks:
  my_network:
    driver: bridge
  apigw_network:
    driver: bridge
volumes:
  esdata:
  ldap_data:
  ldap_config:
  db_data:
services:

  usersocial_ms:
    image: usersocial_ms
    build:
      context: ../usersocial_ms/MS_userSocial
      dockerfile: ./Dockerfile  
    ports:
      - "8000:8000"
    networks:
      - my_network

  comments_ms:
    image: comments_ms
    build:
      context: ../comments_ms
      dockerfile: ./Dockerfile  
    ports:
      - "8082:8082"
    networks:
      - my_network

  music_ms:
    image: music_ms
    build: 
      context: ../music_ms
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - elasticsearch
    environment:
      - SPOTIFY_CLIENT_ID=4bfedb806e3d49db9eeecfe03fe22057
      - SPOTIFY_CLIENT_SECRET=a7c80d1d7d664c058c876c6290fc04db
    networks:
      - my_network
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    environment:
      - discovery.type=single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - my_network
  
  proxy_apigateway:
    image: proxy_apigateway
    container_name: proxy_ag
    build: 
      context: ../appolo_ag_rp
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ../appolo_ag_rp/app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - apigateway
    networks:
      - apigw_network
      - my_network
      
  apigateway:
    image: apigateway
    build:      
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: always
    networks:
      - apigw_network
      - my_network
    depends_on:
      - auth_ms
  auth_ms:
    build:
      context: ../auth_ms
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      SECRET_KEY_BASE: b5fd37d1625555cc045316c41551d68ad20b8c59107d45bd1fc3654aba6dd7eb186a2b20cba71236f659aa2afc0e77e54e36f46d0d3a2f36d8d0e187c063ac8d
      DATABASE_HOST: db
      DATABASE_USER: naimu
      DATABASE_PASSWORD: password
    depends_on:
      - db
      - appolo-ldap
    networks:
      - apigw_network
      - my_network
  db:
    image: postgres:latest
    container_name: auth_ms_db
    environment:
      POSTGRES_DB: apollo_api_development
      POSTGRES_USER: naimu
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - apigw_network
      - my_network
      
  appolo-ldap:
    image: osixia/openldap:1.1.8
    container_name: appolo_ldap
    environment:
      LDAP_ORGANISATION: "Software Architecture"
      LDAP_DOMAIN: "arqsoft.unal.edu.co"
      LDAP_BASE_DN: "dc=arqsoft,dc=unal,dc=edu,dc=co"
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_CONFIG_PASSWORD: "config"
      LDAP_LOG_LEVEL: "256"
    ports:
      - "389:389"
      - "636:636"
    expose:
      - "389"
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
    networks:
      - apigw_network
      - my_network
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "appolo-ldap"
      PHPLDAPADMIN_HTTPS: "false"
      PHPLDAPADMIN_LDAP_DEBUG: "true"
      PHPLDAPADMIN_LDAP_DEBUG_LEVEL: 7
    ports:
      - "8085:80"
    depends_on:
      - appolo-ldap
    networks:
      - apigw_network
      - my_network  
    